version: '3'

networks:
  search-network:
    driver: bridge

services:
  mongo:
    image: mongo:3.4.21-xenial
    ports:
      - 27017:27017
    networks:
      - search-network

  elasticsearch:
    image: elasticsearch:6.8.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - search-network

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - search-network

  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    networks:
      - search-network
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=hotel_search

  zookeeper:
    image: bitnami/zookeeper:3.5.5
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - search-network

  kafka:
    image: bitnami/kafka:2.3.0
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    networks:
      - search-network
